//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RohiniTravels.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeesTransactionDetail
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> StudentServiceId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Active { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsReceived { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string Remark { get; set; }
        public string Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> FeesDate { get; set; }
    }
}
